let products = [
    {
        id: 1001,
        title: "Cat Food, 25lb bag",
        description: "A 25 pound bag of <em>irresistible</em>, organic goodness for your cat.",
        price: 2000,
        image: "images/product-fullsize.png",
        availableInventory: 10,
        rating: 3,
    },
    {
        id: 1002,
        title: "Dog Treats, 15oz",
        description: "Delicious and healthy treats for your furry friend.",
        price: 1200,
        image: "images/dog-treats.png",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 1003,
        title: "Cat Toy, Plush Mouse",
        description: "A soft, squeaky mouse for hours of fun.",
        price: 800,
        image: "images/cat-toy.jpg",
        availableInventory: 10,
        rating: 5,
    },
    {
        id: 1004,
        title: "Dog Food, 30lb bag",
        description: "Nutritious and balanced food for your dog’s health.",
        price: 2500,
        image: "images/dog-food.jpg",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 1005,
        title: "Cat Litter, 40lb bag",
        description: "Odor control and clumping action for a clean litter box.",
        price: 1500,
        image: "images/cat-litter.jpg",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 1006,
        title: "Dog Shampoo, 16oz",
        description: "Gentle and effective shampoo for a shiny coat.",
        price: 1000,
        image: "images/dog-shampoo.png",
        availableInventory: 10,
        rating: 5,
    },
    {
        id: 1007,
        title: "Cat Scratching Post",
        description: "Durable scratching post to keep your cat happy.",
        price: 3000,
        image: "images/scratching-post.jpg",
        availableInventory: 10,
        rating: 4,
    },
    {
        id: 1008,
        title: "Pet Carrier, Small",
        description: "Comfortable and secure carrier for your small pets.",
        price: 4000,
        image: "images/pet-carrier.jpg",
        availableInventory: 10,
        rating: 3,
    }
]
